name: Test AIO Jira Action 

on:
  release:
    types: [published]
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: 	ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: AIO Tests Jira App integration with Github Action
        uses: shanu-ck/Jira-AIO-Action@v1
        with:
          token: ${{ secrets.AIO_API_TOKEN }}
          filePath: "testReport/JsonReport.json"
          jiraProjectKey: "FIR"
          aioCycleKey: "FIR-CY-1"
