name: Test AIO Jira Action 

on: push

jobs:
  build:
    runs-on: 	ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Jira AIO Tests with Github Action
        uses: ShanuDey/Jira-AIO-Action@v1.0.3
        with:
          token: ${{ secrets.AIO_API_TOKEN }}
          filePath: "testReport/JsonReport.json"
          jiraProjectKey: "FIR"
          aioCycleKey: "FIR-CY-1"
